# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ButtplugMcp < Formula
  desc "Buttplug MCP Server"
  homepage "https://github.com/conacademy/buttplug-mcp"
  version "0.0.1"

  on_macos do
    url "https://github.com/conacademy/buttplug-mcp/releases/download/v0.0.1/buttplug-mcp_Darwin_all.tar.gz"
    sha256 "dd299894787fb324f0a4cab6eb8740676d4d194e8f83cbae295037219c57893c"

    def install
      bin.install "buttplug-mcp"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/conacademy/buttplug-mcp/releases/download/v0.0.1/buttplug-mcp_Linux_x86_64.tar.gz"
        sha256 "c5b63a0f1a9ba0cc9d74ed99be415d9e36daf64cdc5b983fd647e6793987df83"

        def install
          bin.install "buttplug-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/conacademy/buttplug-mcp/releases/download/v0.0.1/buttplug-mcp_Linux_arm64.tar.gz"
        sha256 "349e894aa6a83c85b8088bee5eb25fbfff0d8a09255536c78757972646e8b8b7"

        def install
          bin.install "buttplug-mcp"
        end
      end
    end
  end
end
