# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hyap7 < Formula
  desc "TUI for the Half Your Age Plus 7 dating age rule"
  homepage "https://github.com/conacademy/hyap7"
  version "0.1.0"

  on_macos do
    url "https://github.com/conacademy/hyap7/releases/download/v0.1.0/hyap7_Darwin_all.tar.gz"
    sha256 "6e6a9f6f49fcc3b9cd0e2f03985c81b59deb79452445841df69e23fe8bfcdb95"

    define_method(:install) do
      bin.install "hyap7"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conacademy/hyap7/releases/download/v0.1.0/hyap7_Linux_x86_64.tar.gz"
      sha256 "6000d41bf926cea60b2bd9ed1a26844cef3f2b08ff19188db452f283e545a615"
      define_method(:install) do
        bin.install "hyap7"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conacademy/hyap7/releases/download/v0.1.0/hyap7_Linux_arm64.tar.gz"
      sha256 "36454e49302be21fc55f0767c30d9bbf1a56f07e4fe81377c033c1b3ea0f0f7b"
      define_method(:install) do
        bin.install "hyap7"
      end
    end
  end
end
