# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Injest < Formula
  desc "CLI Joke Wrapper"
  homepage "https://github.com/conacademy/injest"
  version "0.0.3"

  on_macos do
    url "https://github.com/conacademy/injest/releases/download/v0.0.3/injest_0.0.3_darwin_all.tar.gz"
    sha256 "8965ef9334f4db7b7c9d20901df60a0d2912ffa39c919f87de9803e3c22c0af1"

    def install
      bin.install "injest"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conacademy/injest/releases/download/v0.0.3/injest_0.0.3_linux_arm64.tar.gz"
      sha256 "b4c132614e818b653ba2c12ec621cb9427f4b377b8237115d8a7e2365e3232f0"

      def install
        bin.install "injest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/conacademy/injest/releases/download/v0.0.3/injest_0.0.3_linux_amd64.tar.gz"
      sha256 "0111a6f32507b328c7ba01bc9397e486b0e08f4605074df5c154dea9eb20d15c"

      def install
        bin.install "injest"
      end
    end
  end
end
