# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Injest < Formula
  desc "CLI Joke Wrapper"
  homepage "https://github.com/conacademy/injest"
  version "0.1.0"

  on_macos do
    url "https://github.com/conacademy/injest/releases/download/v0.1.0/injest_0.1.0_darwin_all.tar.gz"
    sha256 "73bf1849b42556a0a9caf014ea05fdd8e429c49b2e90efd78ae9c0fecf36dc72"

    def install
      bin.install "injest"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conacademy/injest/releases/download/v0.1.0/injest_0.1.0_linux_arm64.tar.gz"
      sha256 "9c6e5ed9ccd9857c31358437dfef553500c628ab27d52f58fc3bf2a664012ad0"

      def install
        bin.install "injest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/conacademy/injest/releases/download/v0.1.0/injest_0.1.0_linux_amd64.tar.gz"
      sha256 "f27f20358c2711f822d82c44f76ab817067126ac48fbe272bb12c0004bd6b0a9"

      def install
        bin.install "injest"
      end
    end
  end
end
